# Generated by Django 3.1.2 on 2020-10-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bookinstance_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='reservation_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
