# Generated by Django 3.1.2 on 2020-10-09 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_bookinstance_reservation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookHistoryRenting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_time', models.DateField(blank=True, null=True)),
                ('borrow_time', models.DateField(blank=True, null=True)),
                ('return_time', models.DateField(blank=True, null=True)),
                ('book_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.bookinstance')),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
