# Generated by Django 3.1.2 on 2020-10-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookhistoryrenting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookhistoryrenting',
            old_name='borrow_time',
            new_name='time_stamp',
        ),
        migrations.RemoveField(
            model_name='bookhistoryrenting',
            name='reservation_time',
        ),
        migrations.RemoveField(
            model_name='bookhistoryrenting',
            name='return_time',
        ),
        migrations.AddField(
            model_name='bookhistoryrenting',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], max_length=1),
        ),
    ]
